baseURL = 'https://blog.nero-lithos.com/'
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
languageCode = 'zh-cn'
title = "Lithos' Blog" # Blog title 
theme = 'ananke1'
hasCJKLanguage = true
canonifyurls = true
pagination.pagerSize = 6

googleAnalytics = ""
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  background_color_class = "bg-black"
  recent_posts_number = 100
  footer_links = [
    { name = "ğŸ’» GitHub", url = "https://github.com/Nerolithos" },
    { name = "ğŸ¨ Pixiv", url = "https://www.pixiv.net/users/107379421" },
    { name = "ğŸ  Home", url = "https://blog.nero-lithos.com/" }
  ]

[services]
  [services.disqus]
    shortname = 'nero-lithos'

[taxonomies]
   category = "categories"
   tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true